/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
import Estructuras.Pila;
import Estructuras.Transporte;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.security.Principal;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class AdicionarTransporte extends javax.swing.JFrame {
    Admin1 v1;
    public Pila b=new Pila(100); 
    /**
     * Creates new form AdicionarTransporte
     */
    public AdicionarTransporte() {
        initComponents();
          setLocationRelativeTo(null);
    }
    public AdicionarTransporte(Admin1 aThis) {
       initComponents();
        this.v1=aThis;
        b=(Pila)CargarTransportes("src/Datos/DatosTransportes.dat");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      /*  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
      //Prueba v1=new Prueba();
        this.v1.setVisible(true);
        this.setVisible(false);
        this.dispose();
        }
        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try {
         String nuevoNombre,nuevoTipo,nuevoId;
           int nuevoNroa,nuevoCost,nuevoIDdestino;
            nuevoNombre=camponom.getText();
            nuevoCost=Integer.parseInt(campocos.getText());
            nuevoId=campoidtrans.getText();
            nuevoTipo=campotipo.getText();
            nuevoNroa=Integer.parseInt(camponroa.getText());
            nuevoIDdestino=Integer.parseInt(campoidd.getText());

            if(!nuevoNombre.equals("")){
             
           Transporte nuevo=new Transporte(nuevoNombre,nuevoTipo,nuevoId,nuevoIDdestino,nuevoNroa,nuevoCost);
             //Hotel nuevo=new Hotel("sdvs", "sdvsdvs","dsvsdv", 1, 50, 150);
            v1.getA().adicionar(nuevo);
            JOptionPane.showMessageDialog(null, "TRANSPORTE AGREGADO EXITOSAMENTE  ");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Insertar datos validos ");
        }
    } */
    
    
    
    
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        camponom = new javax.swing.JTextField();
        campocos = new javax.swing.JTextField();
        campoidtrans = new javax.swing.JTextField();
        camponroa = new javax.swing.JTextField();
        campotipo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        campoidd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel1.setText("Adicionar un Transporte");

        jLabel2.setText("Nombre ");

        jLabel3.setText("Costo");

        jLabel4.setText("IDtransporte");

        jLabel5.setText("Nro de asientos");

        jLabel6.setText("Tipo");

        camponom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camponomActionPerformed(evt);
            }
        });

        campocos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campocosActionPerformed(evt);
            }
        });

        campoidtrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoidtransActionPerformed(evt);
            }
        });

        camponroa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camponroaActionPerformed(evt);
            }
        });

        campotipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campotipoActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("IDdestino");

        campoidd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoiddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jButton1)
                        .addGap(72, 72, 72)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(camponom, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campocos, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoidtrans, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(camponroa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoidd, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(camponom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campocos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoidtrans, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(camponroa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoidd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void camponomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camponomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camponomActionPerformed

    private void campocosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campocosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campocosActionPerformed

    private void campoidtransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoidtransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoidtransActionPerformed

    private void camponroaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camponroaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camponroaActionPerformed

    private void campotipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campotipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campotipoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // TODO add your handling code here:
             try {
         String nuevoNombre,nuevoTipo,nuevoId;
           int nuevoNroa,nuevoCost,nuevoIDdestino;
            nuevoNombre=camponom.getText();
            nuevoCost=Integer.parseInt(campocos.getText());
            nuevoId=campoidtrans.getText();
            nuevoTipo=campotipo.getText();
            nuevoNroa=Integer.parseInt(camponroa.getText());
            nuevoIDdestino=Integer.parseInt(campoidd.getText());

            if(!nuevoNombre.equals("")){
             
           Transporte nuevo=new Transporte(nuevoNombre,nuevoTipo,nuevoId,nuevoIDdestino,nuevoNroa,nuevoCost);
             //Hotel nuevo=new Hotel("sdvs", "sdvsdvs","dsvsdv", 1, 50, 150);
            //v1.getB().adicionar(nuevo);
            b.adicionar(nuevo);
            GuardarTransportes(b, "src/Datos/DatosTransportes.dat");
                    
            JOptionPane.showMessageDialog(null, "TRANSPORTE AGREGADO EXITOSAMENTE  ");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Insertar datos validos ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoiddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoiddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoiddActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 this.v1.setVisible(true);
        this.setVisible(false);
        this.dispose();       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarTransporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarTransporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarTransporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarTransporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarTransporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campocos;
    private javax.swing.JTextField campoidd;
    private javax.swing.JTextField campoidtrans;
    private javax.swing.JTextField camponom;
    private javax.swing.JTextField camponroa;
    private javax.swing.JTextField campotipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

private void GuardarHoteles(Pila hh, String ruta){
        try (ObjectOutputStream salida = new ObjectOutputStream(new FileOutputStream(ruta))){
            salida.writeObject(hh);
            System.out.print("Dato guardado");    
        }catch (IOException e) {
            e.printStackTrace();
        }   
    }
    
    private Object CargarHoteles(String ruta){
        Object dato=null;
        try (ObjectInputStream entrada = new ObjectInputStream(new FileInputStream(ruta))){
            dato= entrada.readObject();
            System.out.print("Datos cargados");    
        }catch (Exception e) {
            System.out.print("No se cargaron"); 
        } 
        return dato;
    }
    private void GuardarTransportes(Pila tt, String ruta){
        try (ObjectOutputStream salida = new ObjectOutputStream(new FileOutputStream(ruta))){
            salida.writeObject(tt);
            System.out.print("Dato guardado");    
        }catch (IOException e) {
            e.printStackTrace();
        }   
    }
    
    private Object CargarTransportes(String ruta){
        Object dato=null;
        try (ObjectInputStream entrada = new ObjectInputStream(new FileInputStream(ruta))){
            dato= entrada.readObject();
            System.out.print("Datos cargados");    
        }catch (Exception e) {
            System.out.print("No se cargaron"); 
        } 
        return dato;
    }
}
