/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Estructuras.*;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Admin1 extends javax.swing.JFrame {
MainTour ve;
    public Pila a=new Pila(100); 
    public Pila b=new Pila(100); 

    public Pila getB() {
        return b;
    }

    public void setB(Pila b) {
        this.b = b;
    }
    Admin1(MainTour aThis) {
        initComponents();
        setLocationRelativeTo(null);
        this.ve=aThis;
        a = ve.getA();
        b = ve.getB();
        a=(Pila)CargarHoteles("src/Datos/DatosHoteles.dat");
        b=(Pila)CargarTransportes("src/Datos/DatosTransportes.dat");
        
    }
// geramos geter y setter para la pila 
    public Pila getA() {
        return a;
    }

    public void setA(Pila a) {
        this.a = a;
    }
    
    public Admin1() {
        initComponents();
          setLocationRelativeTo(null);
          
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        BtnMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pantalla_interfaz = new javax.swing.JTable();
        botonEliminar = new javax.swing.JToggleButton();
        campoid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        BtnMostrar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pantalla_interfazTrans = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        botonEliminar1 = new javax.swing.JToggleButton();
        campoidtRA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        reservas = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campoId = new javax.swing.JTextField();
        btSumar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnMostrar.setText("Mostrar");
        BtnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 73, 30));

        jScrollPane1.setViewportView(pantalla_interfaz);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 310, 190));

        botonEliminar.setText("ELIMINAR HOTEL");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        campoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoidActionPerformed(evt);
            }
        });
        getContentPane().add(campoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 71, -1));

        jLabel2.setText("PILA DE HOTELES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jButton3.setText("REGRESAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 122, -1));

        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("ELIMINAR UN HOTEL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 53, 135, -1));

        jLabel5.setText("Ingrese ID Hotel");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 96, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("PANEL DE ADMINISTRACION ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, -1));

        jButton4.setText("ADICIONAR UN HOTEL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 180, 30));

        jButton5.setText("ADICIONAR UN TRANSPORTE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 180, 30));

        BtnMostrar1.setText("Mostrar");
        BtnMostrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMostrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMostrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 73, 30));

        jScrollPane2.setViewportView(pantalla_interfazTrans);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 340, 190));

        jLabel7.setText("PILA TRANSPORTES");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        botonEliminar1.setText("ELIMINAR TRANSPORTE");
        botonEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminar1ActionPerformed(evt);
            }
        });
        getContentPane().add(botonEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        getContentPane().add(campoidtRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 71, -1));

        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("ELIMINAR UN TRASPORTE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 135, -1));

        jLabel9.setText("Ingrese ID Transporte");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        reservas.setText("VEER RESERVAS Y CLIENTES");
        reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservasActionPerformed(evt);
            }
        });
        getContentPane().add(reservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FONDO.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 450));

        jLabel3.setText("Obtener  el costo total de los hoteles del destino X");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 275, 40));

        jLabel1.setText("ingrese id destino");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, -1));

        campoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdActionPerformed(evt);
            }
        });
        getContentPane().add(campoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 115, -1));

        btSumar.setText("SUMAR");
        btSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSumarActionPerformed(evt);
            }
        });
        getContentPane().add(btSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 109, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMostrarActionPerformed
      a=(Pila)CargarHoteles("src/Datos/DatosHoteles.dat");
      String titulos[]={"nombre","direccion","id hotel ","IDdestino", "nro de habitaciones", "costo/noche "};
        //POR DEFECTO PORQUE NO SABEMOS EL TAMA;O REAL
        DefaultTableModel pantalla =new DefaultTableModel(null,titulos);
        //recorrer para mostra cada objeto de la pila 
        Pila aux=new Pila(100);
        while(!a.esVacia()){
            Hotel x=(Hotel)a.eliminar();
            String fila[]={x.getNom(),x.getDire(),x.getIDhotel(),Integer.toString(x.getIDdestino()),Integer.toString(x.getNroh()),Integer.toString(x.getCostoh())};
        pantalla.addRow(fila);
        aux.adicionar(x);
        }
        a.vaciar(aux);
        pantalla_interfaz.setModel(pantalla);
    }//GEN-LAST:event_BtnMostrarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        //para no mandar errores try 
        try {
           
            Pila aux=new Pila(100);
             String idx=campoid.getText();
            int existe=0;
            while(!a.esVacia()){
            Hotel x=(Hotel)a.eliminar();
            if(x.getIDhotel().equals(idx)){
               existe=1;
            
            }else {aux.adicionar(x);
            }
            }  a.vaciar(aux);
            if(existe==1){
            JOptionPane.showMessageDialog(null, "hotel eliminado");
            GuardarHoteles(a, "src/Datos/DatosHoteles.dat");
       
            a=(Pila)CargarHoteles("src/Datos/DatosHoteles.dat");
            }
            
            else{
            JOptionPane.showMessageDialog(null, "hotel no eliminado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "insertar dato valido ");
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void campoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdActionPerformed

    private void btSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSumarActionPerformed
         try {
           
            Pila aux=new Pila(100);
            int idx=Integer.parseInt(campoId.getText());
            int existe=0;
            int suma=0;
            int  nombre=0;
            while(!a.esVacia()){
            Hotel x=(Hotel)a.eliminar();
            if(x.getIDdestino()==idx){
                suma=suma+x.getCostoh();
                nombre=x.getIDdestino();
            }aux.adicionar(x);
            }a.vaciar(aux);
            JOptionPane.showMessageDialog(null, "suma total del costo de hoteles del destino : "+nombre+"es "+suma);
            }
            
         catch (Exception e) {
            JOptionPane.showMessageDialog(null, "insertar dato valido ");
        }
    }//GEN-LAST:event_btSumarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ve.setA(a);
        ve.setB(b);
        this.ve.setVisible(true);
        this.setVisible(false);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        AdicionarHotel v2=new AdicionarHotel(this);
        v2.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        AdicionarTransporte v3=new AdicionarTransporte(this);
        v3.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void BtnMostrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMostrar1ActionPerformed
        b=(Pila)CargarTransportes("src/Datos/DatosTransportes.dat");
        String titulos[]={"nombre","tipo :","id Transporte ","id destino ", "nro de asientos", "costo "};
        //POR DEFECTO PORQUE NO SABEMOS EL TAMA;O REAL
        DefaultTableModel pantalla =new DefaultTableModel(null,titulos);
        //recorrer para mostra cada objeto de la pila 
        Pila aux=new Pila(100);
        while(!b.esVacia()){
            Transporte y=(Transporte)b.eliminar();
            String fila[]={y.getNom(),y.getTipo(),y.getIDtransporte(),Integer.toString(y.getIDdestino()),Integer.toString(y.getNroa()),Integer.toString(y.getCostot())};
        pantalla.addRow(fila);
        aux.adicionar(y);
        }
        b.vaciar(aux);
        pantalla_interfazTrans.setModel(pantalla);
    }//GEN-LAST:event_BtnMostrar1ActionPerformed

    private void botonEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminar1ActionPerformed
      //para no mandar errores try 
        try {
           
            Pila aux2=new Pila(100);
             String idx=campoidtRA.getText();
            int existe=0;
            while(!b.esVacia()){
            Transporte x=(Transporte)b.eliminar();
            if(x.getIDtransporte().equals(idx)){
               existe=1;
            
            }else {aux2.adicionar(x);
            }
            }  b.vaciar(aux2);
            if(existe==1){
            JOptionPane.showMessageDialog(null, "Transporte eliminado");
            GuardarTransportes(b, "src/Datos/DatosTransportes.dat");
        
            b=(Pila)CargarTransportes("src/Datos/DatosTransportes.dat");
            }
            else{
            JOptionPane.showMessageDialog(null, "Transporte no eliminado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "insertar dato valido ");
        }
    }//GEN-LAST:event_botonEliminar1ActionPerformed

    private void campoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoidActionPerformed

    private void reservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservasActionPerformed
        Reservas_Clientes most = new Reservas_Clientes(this);
        most.setVisible(true);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_reservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMostrar;
    private javax.swing.JButton BtnMostrar1;
    private javax.swing.JToggleButton botonEliminar;
    private javax.swing.JToggleButton botonEliminar1;
    private javax.swing.JButton btSumar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoId;
    private javax.swing.JTextField campoid;
    private javax.swing.JTextField campoidtRA;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable pantalla_interfaz;
    private javax.swing.JTable pantalla_interfazTrans;
    private javax.swing.JButton reservas;
    // End of variables declaration//GEN-END:variables

private void GuardarHoteles(Pila hh, String ruta){
        try (ObjectOutputStream salida = new ObjectOutputStream(new FileOutputStream(ruta))){
            salida.writeObject(hh);
            System.out.print("Dato guardado");    
        }catch (IOException e) {
            e.printStackTrace();
        }   
    }
    
    private Object CargarHoteles(String ruta){
        Object dato=null;
        try (ObjectInputStream entrada = new ObjectInputStream(new FileInputStream(ruta))){
            dato= entrada.readObject();
            System.out.print("Datos cargados");    
        }catch (Exception e) {
            System.out.print("No se cargaron"); 
        } 
        return dato;
    }
    private void GuardarTransportes(Pila tt, String ruta){
        try (ObjectOutputStream salida = new ObjectOutputStream(new FileOutputStream(ruta))){
            salida.writeObject(tt);
            System.out.print("Dato guardado");    
        }catch (IOException e) {
            e.printStackTrace();
        }   
    }
    
    private Object CargarTransportes(String ruta){
        Object dato=null;
        try (ObjectInputStream entrada = new ObjectInputStream(new FileInputStream(ruta))){
            dato= entrada.readObject();
            System.out.print("Datos cargados");    
        }catch (Exception e) {
            System.out.print("No se cargaron"); 
        } 
        return dato;
    }
}
